{% set version = '0.2.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scutrboot
  version: {{ version|replace("-", "_") }}

source:
  path: ../

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base  {{ r_base }}
    - r-matrix
    - bioconductor-biocparallel
    - bioconductor-singlecellexperiment
    - bioconductor-sparsematrixstats

  run:
    - r-base
    - r-matrix
    - bioconductor-biocparallel
    - bioconductor-singlecellexperiment
    - bioconductor-sparsematrixstats

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('scutrboot')"           # [not win]
    - "\"%R%\" -e \"library('scutrboot')\""  # [win]

about:
  home: https://github.com/mfansler/scutrboot
  license: GPL-3
  summary: A set of bootstrap-based statistical methods for analyzing 3\u2032 UTR
    quantification data derived from single-cell RNA-sequencing.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
